language: cpp

compiler:
  - gcc


addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov


script: ./build-all.sh

notifications:
   email: false



